export default {
  produkty: [
    {
      name: "Ponožky Shoe Liner",
      slug: "shoeLiner",
      image: "shoeLiner.jpg",
      id: 8401,
      description: "Nízké ponožky s plochými švy s elastanem, který zaručuje pohodlné nošení. Integrovaný šev na špici. Logo a velikost jsou vpletené do tkaniny.",
      colors: "black, grey",
    },
    {
      name: "Ponožky Liner Classic",
      slug: "linerClassic",
      image: "linerClassic.jpg",
      id: 8411,
      description: "Ponožky s plochými švy s elastanem, který zaručuje pohodlné nošení. Integrovaný šev na špici. Logo a velikost jsou vpletené do tkaniny.",
      colors: "black, grey",
    },
    {
      name: "Ponožky Liner Knee-high",
      slug: "linerKneeHigh",
      image: "linerKneeHigh.jpg",
      id: 8481,
      description: "Podkolenky s plochými švy s elastanem, který zaručuje pohodlné nošení. Integrovaný šev na špici. Logo a velikost jsou vpletené do tkaniny.",
      colors: "black, grey",
    },
    {
      name: "Ponožky Skilled Liner Short",
      slug: "skilledLinerShort",
      image: "skilledLinerShort.jpg",
      id: 8801,
      description: "Ponožky s technicky propracovanou konstrukcí s plochými švy. Síťovinové panely zvyšují jejich funkčnost. Díky kombinovaným úpletům sedí ponožky perfektně na nohou, což zabraňuje vzniku puchýřů, a zároveň poskytují dostatečnou podporu a ventilaci přesně tam, kde je to potřeba.",
      colors: "black, grey",
    },
    {
      name: "Ponožky Skilled Liner Classic",
      slug: "skilledLinerClassic",
      image: "skilledLinerClassic.jpg",
      id: 8811,
      description: "Středně vysoké ponožky s technicky propracovanou konstrukcí s plochými švy. Síťovinové panely zvyšují jejich funkčnost. Díky kombinovaným úpletům sedí ponožky perfektně na nohou, což zabraňuje vzniku puchýřů, a zároveň poskytují dostatečnou podporu a ventilaci přesně tam, kde je to potřeba.",
      colors: "dark grey/grey, dark navy/nordic blue",
    },
    {
      name: "Ponožky Skilled Liner Knee-high",
      slug: "skilledLinerKneeHigh",
      image: "skilledLinerKneeHigh.jpg",
      id: 8821,
      description: "Podkolenky s technicky propracovanou konstrukcí s plochými švy. Síťovinové panely zvyšují jejich funkčnost. Díky kombinovaným úpletům sedí ponožky perfektně na nohou, což zabraňuje vzniku puchýřů, a zároveň poskytují dostatečnou podporu a ventilaci přesně tam, kde je to potřeba.",
      colors: "dark grey/grey, dark navy/nordic blue",
    },
    {
      name: "Ponožky Classic 200",
      slug: "ponozkyClassic200",
      image: "ponozkyClassic200.jpg",
      id: 8412,
      description: "Ponožky s froté úpletem v oblasti chodidla a s žebrovaným komínkem. Ve 200 gramáži.",
      colors: "black, gey, dark navy, pine green",
    },
    {
      name: "Ponožky Skilled Classic 400",
      slug: "ponozkySkilledClassic400",
      image: "ponozkySkilledClassic400.jpg",
      id: 8814,
      description: "Středně vysoké ponožky s technicky propracovanou konstrukcí s plochými švy. Díky kombinaci podpůrných úpletů s froté úpletem sedí ponožky perfektně na nohou, což zabraňuje vzniku puchýřů, a zároveň poskytují dostatečnou podporu a izolaci přesně tam, kde je to potřeba.",
      colors: "dark grey/black, dark navy/nordic blue",
    },
    {
      name: "Ponožky Skilled Knee-high 400",
      slug: "ponozkySkilledKneeHigh400",
      image: "ponozkySkilledKneeHigh400.jpg",
      id: 8824,
      description: "Podkolenky s technicky propracovanou konstrukcí s plochými švy. Díky kombinaci podpůrných úpletů s froté úpletem sedí ponožky perfektně na nohou, což zabraňuje vzniku puchýřů, a zároveň poskytují dostatečnou podporu a izolaci přesně tam, kde je to potřeba.",
      colors: "dark grey/black, dark navy/nordic blue",
    },
    {
      name: "Ponožky Classic 400",
      slug: "ponozkyClassic400",
      image: "ponozkyClassic400.jpg",
      id: 8414,
      description: "Teplejší ponožky s froté úpletem na chodidlech i na komínku. Ve 400 gramáži.",
      colors: "black, gey, dark navy, pine green",
    },
    {
      name: "Ponožky Classic Logo 400",
      slug: "ponozkyClassicLogo400",
      image: "ponozkyClassicLogo400.jpg",
      id: 8424,
      description: "Teplejší ponožky s froté úpletem v oblasti chodidla a s žebrovaným komínkem s vpleteným logem.",
      colors: "black, gey, dark navy",
    },
    {
      name: "Ponožky Knee-high 400",
      slug: "ponozkyKneeHigh400",
      image: "ponozkyKneeHigh400.jpg",
      id: 8484,
      description: "Teplejší podkolenky s froté úpletem na chodidlech i na komínku.",
      colors: "black",
    },
    {
      name: "Ponožky Classic 600",
      slug: "ponozkyClassic600",
      image: "ponozkyClassic600.jpg",
      id: 8416,
      description: "Teplé ponožky s froté úpletem na chodidlech i na komínku. Ve 600 gramáži.",
      colors: "black, gey, dark navy, pine green",
    },
    {
      name: "Ponožky Knee-high 600",
      slug: "ponozkyKneeHigh600",
      image: "ponozkyKneeHigh600.jpg",
      id: 8486,
      description: "Teplé podkolenky s froté úpletem na chodidlech i na komínku. Ve 600 gramáži.",
      colors: "black, gey, dark navy, pine green",
    },
    {
      name: "Ponožky Classic 800",
      slug: "ponozkyClassic800",
      image: "ponozkyClassic800.jpg",
      id: 8418,
      description: "Velmi teplé ponožky s froté úpletem na chodidlech i na komínku. Ve 800 gramáži.",
      colors: "black, gey, pine green",
    },
    {
      name: "Headband 200",
      slug: "headband200",
      image: "headband200.jpg",
      id: 9612,
      description: "Čelenka s dvouvrstým froté úpletem. Tento úplet zajišťuje kvalitní teleplou izolaci, zároveň však rychle odvádí přebytečné teplo při vyšším výkonu.",
      colors: "black",
    },
    {
      name: "Čepice Beanie Lite",
      slug: "beanieLite",
      image: "beanieLite.jpg",
      id: 9621,
      description: "Pohodlná čepice z dvouvrstvého materiálu Lite pro optimální termoregulaci.",
      colors: "black, nordic blue, pine green",
    },
    {
      name: "Čepice Cap 400",
      slug: "cap400",
      image: "cap400.jpg",
      id: 9624,
      description: "Teplejší dvouvrstvá čepice s froté úpletem ve 400 gramáži pro optimální termoregulaci.",
      colors: "black",
    },
    {
      name: "Tube Lite",
      slug: "tubeLite",
      image: "tubeLite.jpg",
      id: 9601,
      description: "Tunelový šátek, který můžete využít jako nákrčník, čelenku nebo čepici. 40 cm dlouhý.",
      colors: "black, nordic blue, pine green",
    },
    {
      name: "Tube 200",
      slug: "tube200",
      image: "tube200.jpg",
      id: 9602,
      description: "Tunelový šátek z kruhového froté úpletu. Lze jej použít jako čelenku nebo nákrčník. 30 cm dlouhý.",
      colors: "black",
    },
    {
      name: "Čepice Helmet Cap 400",
      slug: "helmetCap400",
      image: "helmetCap400.jpg",
      id: 9644,
      description: "Pohodlná vložka pod helmu, která zakryje hlavu i krk.",
      colors: "black, pine green",
    },
    {
      name: "Balaclava Lite",
      slug: "balaclvaLite",
      image: "balaclvaLite.jpg",
      id: 9651,
      description: "Přiléhavá a pohodlná kukla. Z tenkého materiálu Lite, ale přesto nabízí skvělou ochranu v chladném počasí. Ploché švy zabraňují tření, takže kuklu lze použít pod přilbou.",
      colors: "black, pine green",
    },
    {
      name: "Balaclava 200",
      slug: "balaclava200",
      image: "balaclava200.jpg",
      id: 9652,
      description: "Kukla s jediným otvorem, který lze nastavit tak, že zakrývá vše kromě očí. Spodní lem lze stáhnout pod nos nebo až pod bradu.",
      colors: "black, pine green",
    },
    {
      name: "Balaclava 400",
      slug: "balaclava400",
      image: "balaclava400.jpg",
      id: 9654,
      description: "Teplejší kukla s jediným otvorem, který lze nastavit tak, že zakrývá vše kromě očí. Spodní lem lze stáhnout pod nos nebo až pod bradu. Prodloužený model.",
      colors: "black, pine green",
    },
    {
      name: "Rukavice Mittens thin 400",
      slug: "mittensThin400",
      image: "mittensThin400.jpg",
      id: 9744,
      description: "Tenké rukavice s jednovrstvým froté úpletem. Ideální jako vložka pod palčáky. Šev je na vnější straně.",
      colors: "black",
    },
    {
      name: "Rukavice Mittens 400",
      slug: "mittens400",
      image: "mittens400.jpg",
      id: 9754,
      description: "Palčáky z dvouvrstvého froté materiálu pro optimální termoregulaci.",
      colors: "black, pine green",
    },
    {
      name: "Wrist Gaiter 200",
      slug: "wristGaiter200",
      image: "wristGaiter200.jpg",
      id: 9672,
      description: "Návleky na ruce s dírkou na palec. Kruhový úplet s froté úpletem uvnitř. Vypletené Woolpower logo. Délka 18 cm.",
      colors: "black, grey",
    },
    {
      name: "Belly Warmer 200",
      slug: "bellyWarmer200",
      image: "bellyWarmer200.jpg",
      id: 9512,
      description: "Hřejivý pás pro těhotné s elastickým vrchním lemem bez podélných švů. Hladký úplet zvenku a froté úplet uvnitř.",
      colors: "black",
    },
  ]
}