export default {
  produkty: [
    {
      name: "Zip Turtleneck LITE",
      slug: "zipTurtleneckLite",
      image: "ZipTurtleneckLITE.jpg",
      id: 1,
      description: "Rolák je vhodný do chladnějšíh počasí. Díky zipu lze regulovat ventilaci. Raglánové rukávy a ploché švy dodají na pohodlnosti při nošení.",
      colors: ["black", "pine green"],
    },
    {
      name: "Crewneck LITE",
      slug: "crewneckLite",
      image: "CrewneckLITE.jpg",
      id: 2,
      description: "Doplnit!",
      colors: ["black", "pine green", "nordic blue"],
    },
    {
      name: "Tee LITE",
      slug: "teeLite",
      image: "TeeLITE.jpg",
      id: 3,
      description: "Doplnit!",
      colors: ["black", "pine green", "nordic blue"],
    },
    {
      name: "Lonng Johns W's LITE",
      slug: "longJohnsWsLite",
      image: "LongJohnWsLITE.jpg",
      id: 4,
      description: "Doplnit!",
      colors: ["black", "pine green", "nordic blue"],
    },
    {
      name: "Long Johns M's LITE",
      slug: "longJohnsMsLite",
      image: "LongJohnsMsLITE.jpg",
      id: 5,
      description: "Doplnit!",
      colors: ["black", "pine green", "nordic blue"],
    },
    {
      name: "3/4 Long Johns M's LITE",
      slug: "34longJohnsMsLite",
      image: "34LongJohnsMsLITE .jpg",
      id: 6,
      descrription: "Doplnit!",
      colors: ["black"],
    },
    {
      name: "3/4 Long Johns W's LITE",
      slug: "34longJohnsWsLite",
      image: "34LongJohnsWsLITE .jpg",
      id: 7,
      descrription: "Doplnit!",
      colors: ["black"],
    },
    {
      name: "Briefs Xlong W's LITE",
      slug: "briefsXlongWsLite",
      image: "BriefsXLongWsLITE.jpg",
      id: 8,
      descrription: "Doplnit!",
      colors: ["black"],
    },
    {
      name: "Boxer Xlong M's LITE",
      slug: "boxerXlongMsLite",
      image: "BoxerXLongMsLITE.jpg",
      id: 9,
      descrription: "Doplnit!",
      colors: ["black"],
    },
    {
      name: "Hipster W's LITE",
      slug: "hipsterWsLite",
      image: "HipstersWsLITE.jpg",
      id: 10,
      descrription: "Doplnit!",
      colors: ["black"],
    },
    {
      name: "Boxers M's LITE",
      slug: "boxerMsLite",
      image: "BoxerMsLITE.jpg",
      id: 11,
      descrription: "Doplnit!",
      colors: ["black"],
    }
  ]
}