export default {
  produkty: [
    {
      name: "Zip Turtleneck LITE",
      slug: "zipTurtleneckLITE",
      image: "ZipTurtleneckLITE.jpg",
      id: 1,
      description: "Rolák je vhodný do chladnějšíh počasí. Díky zipu lze regulovat ventilaci. Raglánové rukávy a ploché švy dodají na pohodlnosti při nošení.",
      colors: "black, pine green",
    },
    {
      name: "Crewneck LITE",
      slug: "crewneckLITE",
      image: "CrewneckLITE.jpg",
      id: 2,
      description: "Doplnit!",
      colors: "black, pine green, nordic blue",
    },
    {
      name: "Tee LITE",
      slug: "teeLITE",
      image: "TeeLITE.jpg",
      id: 3,
      description: "Doplnit!",
      colors: "black, pine green, nordic blue",
    },
    {
      name: "Lonng Johns W's LITE",
      slug: "longJohnsWsLITE",
      image: "LongJohnWsLITE.jpg",
      id: 4,
      description: "Doplnit!",
      colors: "black, pine green, nordic blue",
    },
    {
      name: "Long Johns M's LITE",
      slug: "longJohnsMsLITE",
      image: "LongJohnsMsLITE.jpg",
      id: 5,
      description: "Doplnit!",
      colors: "black, pine green, nordic blue",
    },
    {
      name: "3/4 Long Johns M's LITE",
      slug: "34longJohnsMsLITE",
      image: "34LongJohnsMsLITE .jpg",
      id: 6,
      description: "Doplnit!",
      colors: "black",
    },
    {
      name: "3/4 Long Johns W's LITE",
      slug: "34longJohnsWsLITE",
      image: "34LongJohnsWsLITE .jpg",
      id: 7,
      description: "Doplnit!",
      colors: "black",
    },
    {
      name: "Briefs Xlong W's LITE",
      slug: "briefsXlongWsLITE",
      image: "BriefsXLongWsLITE.jpg",
      id: 8,
      description: "Doplnit!",
      colors: "black",
    },
    {
      name: "Boxer Xlong M's LITE",
      slug: "boxerXlongMsLITE",
      image: "BoxerXLongMsLITE.jpg",
      id: 9,
      description: "Doplnit!",
      colors: "black",
    },
    {
      name: "Hipster W's LITE",
      slug: "hipsterWsLITE",
      image: "HipstersWsLITE.jpg",
      id: 10,
      description: "Doplnit!",
      colors: "black",
    },
    {
      name: "Boxers M's LITE",
      slug: "boxerMsLITE",
      image: "BoxerMsLITE.jpg",
      id: 11,
      description: "Doplnit!",
      colors: "black",
    }
  ]
}