export default {
  produkty: [
    {
      name: "Zip Turtleneck LITE",
      slug: "zipTurtleneckLITE",
      image: "ZipTurtleneckLITE.jpg",
      id: 7221,
      description: "Vyšší límec se zipem nabízí lepší ochranu v chladném počasí. Podélné švy jsou umístěny v zadní části pro optimální pohodlí. Rukávy mají raglánové švy, které zabraňují oděru při nošení batohu. Zadní část je prodloužená.",
      colors: "black, pine green",
      sex: "Unisex",
    },
    {
      name: "Crewneck LITE",
      slug: "crewneckLITE",
      image: "CrewneckLITE.jpg",
      id: 7111,
      description: "Podélné švy jsou umístěny v zadní části pro optimální pohodlí. Rukávy mají raglánové švy, které zabraňují oděru při nošení batohu. Zadní část je prodloužená.",
      colors: "black, pine green, nordic blue",
      sex: "Unisex",
    },
    {
      name: "Tee LITE",
      slug: "teeLITE",
      image: "TeeLITE.jpg",
      id: 7101,
      description: "Podélné švy jsou umístěny v zadní části pro optimální pohodlí. Krátké rukávy mají raglánové švy, které zabraňují oděru při nošení batohu. Zadní část je prodloužená.",
      colors: "black, pine green, nordic blue",
      sex: "Unisex",
    },
    {
      name: "Lonng Johns W's LITE",
      slug: "longJohnsWsLITE",
      image: "LongJohnWsLITE.jpg",
      id: 4341,
      description: "Spodky, které poskytnou kvalitní izolaci a odvod vlhkosti od těla. Jedinečný úplet s pouze jedním podélným švem a zároveň bez vnitřních švů. Pas se všitým logem je vyroben z hebkého a elastického materiálu.",
      colors: "black, pine green, nordic blue",
      sex: "Dámské",
    },
    {
      name: "Long Johns M's LITE",
      slug: "longJohnsMsLITE",
      image: "LongJohnsMsLITE.jpg",
      id: 6341,
      description: "Spodky, které poskytnou kvalitní izolaci a odvod vlhkosti od těla. Jedinečný úplet s pouze jedním podélným švem a zároveň bez vnitřních švů. Pas se všitým logem je vyroben z hebkého a elastického materiálu.",
      colors: "black, pine green, nordic blue",
      sex: "Pánské",
    },
    {
      name: "3/4 Long Johns M's LITE",
      slug: "34longJohnsMsLITE",
      image: "34LongJohnsMsLITE .jpg",
      id: 6331,
      description: "Spodky, které poskytnou kvalitní izolaci a odvod vlhkosti od těla. Jedinečný úplet s pouze jedním podélným švem a zároveň bez vnitřních švů. Ideální v kombinaci s vysokými ponožkami či podkolenkami. Pas se všitým logem je vyroben z hebkého a elastického materiálu.",
      colors: "black",
      sex: "Pánské",
    },
    {
      name: "3/4 Long Johns W's LITE",
      slug: "34longJohnsWsLITE",
      image: "34LongJohnsWsLITE .jpg",
      id: 4331,
      description: "Spodky, které poskytnou kvalitní izolaci a odvod vlhkosti od těla. Jedinečný úplet s pouze jedním podélným švem a zároveň bez vnitřních švů. Ideální v kombinaci s vysokými ponožkami či podkolenkami. Pas se všitým logem je vyroben z hebkého a elastického materiálu.",
      colors: "black",
      sex: "Dámské",
    },
    {
      name: "Briefs Xlong W's LITE",
      slug: "briefsXlongWsLITE",
      image: "BriefsXLongWsLITE.jpg",
      id: 4311,
      description: "Dámské boxerky určené k nošení jako spodní prádlo, které poskytnou kvalitní izolaci a odvod vlhkosti od těla. Prodloužený střih zajistí větší tepelný komfort na stehnech. Pas se všitým logem je vyroben z hebkého a elastického materiálu.",
      colors: "black",
      sex: "Dámské",
    },
    {
      name: "Boxer Xlong M's LITE",
      slug: "boxerXlongMsLITE",
      image: "BoxerXLongMsLITE.jpg",
      id: 6311,
      description: "Boxerky určené k nošení jako spodní prádlo, které poskytnou kvalitní izolaci a odvod vlhkosti od těla. Prodloužený design zajistí extra tepelný komfort pro vaše velké svalové skupiny. Pas se všitým logem je vyroben z hebkého a elastického materiálu.",
      colors: "black",
      sex: "Pánské",
    },
    {
      name: "Hipster W's LITE",
      slug: "hipsterWsLITE",
      image: "HipstersWsLITE.jpg",
      id: 4301,
      description: "Kalhotky určené k nošení jako spodní prádlo, které poskytnou kvalitní izolaci a odvod vlhkosti od těla. Pas se všitým logem je vyroben z hebkého a elastického materiálu.",
      colors: "black",
      sex: "Dámské",
    },
    {
      name: "Boxers M's LITE",
      slug: "boxerMsLITE",
      image: "BoxerMsLITE.jpg",
      id: 6321,
      description: "Boxerky určené k nošení jako spodní prádlo, které poskytnou kvalitní izolaci a odvod vlhkosti od těla. Pas se všitým logem je vyroben z hebkého a elastického materiálu.",
      colors: "black",
      sex: "Pánské",
    }
  ]
}