export default {
  produkty: [
    {
      name: "Long Johns W's Protection LITE",
      slug: "longJohndWsProtectionLITE",
      image: "longJohndWsProtectionLITE.jpg",
      id: 4361,
      description: "Dlouhé tenčí nohavice pro ženy splňující normy EU pro práci. S plochými švy a elastickým pasem.",
      colors: "anthracite",
    },
    {
      name: "Long Johns M's Protection LITE",
      slug: "longJohndMsProtectionLITE",
      image: "longJohndMsProtectionLITE.jpg",
      id: 6361,
      description: "Dlouhé tenčí nohavice pro muže splňující normy EU pro práci. S plochými švy a elastickým pasem.",
      colors: "anthracite",
    },
    {
      name: "Boxer Protection LITE",
      slug: "boxerProtectionLITE",
      image: "boxerProtectionLITE.jpg",
      id: 7591,
      description: "Unisexové oxerky určené k nošení jako spodní prádlo, které poskytnou kvalitní izolaci a odvod vlhkosti od těla. S plochými švy a elastickým pasem.",
      colors: "anthracite",
    },
    {
      name: "Socks Knee-high Protection 400",
      slug: "socksKneeHighProtection400",
      image: "socksKneeHighProtectionLITE.jpg",
      id: 8444,
      description: "Podkolenky s froté úpletem, extra pružné v oblasti kotníku a lemu ponožek pro větší pohodlí při nošení.",
      colors: "anthracite",
    },
    {
      name: "Socks Protection 400",
      slug: "socksProtection400",
      image: "socksProtection400.jpg",
      id: 8434,
      description: "Ponožky s froté úpletem, extra pružné v oblasti kotníku a lemu ponožek pro větší pohodlí při nošení.",
      colors: "anthracite",
    },
    {
      name: "Helmet Cap Protection 400",
      slug: "helmetCapProtection400",
      image: "helmetCapProtection400.jpg",
      id: 8434,
      description: "Pohodlná vložka pod helmu, která zakryje hlavu i krk.",
      colors: "anthracite",
    },
    {
      name: "Balaclava Protection LITE",
      slug: "balaclavaProtectionLite",
      image: "balaclavaProtectionLite.jpg",
      id: 96610300,
      description: "Kukla s jediným otvorem, který lze nastavit tak, že zakrývá vše kromě očí.",
      colors: "anthracite",
    },
    {
      name: "Vest Protection 400",
      slug: "vestProtection400",
      image: "vestProtection400.jpg",
      id: 7524,
      description: "Celorozepínací vesta s vysokým límcem. Vyrobena z kruhového úpletu s rovným spodním lemem.",
      colors: "anthracite",
    },
    {
      name: "Zip Turtleneck Protection 400",
      slug: "zipTurtleProtection400",
      image: "zipTurtleProtection400.jpg",
      id: 7514,
      description: "Rolák s dlouhým rukávem a krátkým zipem, je vyroben z kruhového úpletu a nemá podélné švy. Zadní strana je delší pro zvýšení komfortu nošení. Manžety jsou vpletené do tkaniny.",
      colors: "anthracite",
    },
    {
      name: "Full Zip Jacket Protection 400",
      slug: "fullZipJcktProtection400",
      image: "fullZipJcktProtection400.jpg",
      id: 7504,
      description: "Celorozepínací mikina s vysokým límcem a s prodlouženým zadním dílem. Manžety mají dírky na palce.",
      colors: "anthracite",
    },
    {
      name: "Zip Turtleneck Protection LITE",
      slug: "zipTurtleProtectionLITE",
      image: "zipTurtleProtectionLITE.jpg",
      id: 7511,
      description: "Vyšší límec se zipem nabízí lepší ochranu v chladném počasí. Podélné švy jsou umístěny v zadní části pro optimální pohodlí. Rukávy mají raglánové švy, které zabraňují oděru. Zadní část je prodloužená.",
      colors: "anthracite",
    },
    {
      name: "Balaclava Protection 400",
      slug: "balaclavaProtection400",
      image: "balaclavaProtection400.jpg",
      id: 9554,
      description: "Kukla s jediným otvorem, který lze nastavit tak, že zakrývá vše kromě očí.",
      colors: "anthracite",
    },
    {
      name: "Crewneck Protection LITE",
      slug: "crewneckProtectionLITE",
      image: "crewneckProtectionLITE.jpg",
      id: 7291,
      description: "Podélné švy jsou umístěny v zadní části pro optimální pohodlí. Rukávy mají raglánové švy. Zadní část je prodloužená.",
      colors: "anthracite",
    },
    {
      name: "Long Johns Protection 400",
      slug: "longJohnsProtection400",
      image: "longJohnsProtection400.jpg",
      id: 7534,
      description: "Dlouhé spodky s kruhovým úpletem bez podélných švů. Klínovitá vsázka zvyšuje komfort nošení. Manžety jsou vpletené do tkaniny.",
      colors: "anthracite",
    },
    {
      name: "Long Johns with fly Protection 400",
      slug: "longJohnsFlyProtection400",
      image: "longJohnsFlyProtection400.jpg",
      id: 6544,
      description: "Dlouhé spodky s kruhovým úpletem bez podélných švů a s poklopcem. Klínovitá vsázka zvyšuje komfort nošení. Manžety jsou vpletené do tkaniny.",
      colors: "anthracite",
    },
  ]
}