export default {
  produkty: [
    {
      name: "Zip Turtleneck 200",
      slug: "zipTurtleneck200",
      image: "zipTurtleneck200.jpg",
      id: 7222,
      description: "Rolák s dlouhým rukávem a krátkým zipem, je vyroben z kruhového úpletu a nemá podélné švy. Zadní strana je delší pro zvýšení komfortu nošení. Manžety jsou vpletené do tkaniny.",
      colors: "black, dark navy, grey, pine green",
      insulation: 200,
      sex: "Unisex",
    },
    {
      name: "Crewneck 200",
      slug: "crewneck200",
      image: "crewneck200.jpg",
      id: 7112,
      description: "Svetr s kulatým výstřihem, vyrobený z kruhového úpletu bez podélných švů. Zadní strana je delší pro zvýšení komfortu nošení. Manžety jsou vpletené do tkaniny.",
      colors: "black, dark navy, grey, pine green",
      insulation: 200,
      sex: "Unisex",
    },
    {
      name: "Tee 200",
      slug: "tee200",
      image: "tee200.jpg",
      id: 7102,
      description: "Spodní vrstva s krátkým rukávem a kulatým výstřihem. Kruhový úplet bez podélných švů. Manžety jsou pružné.",
      colors: "black, dark navy, grey, pine green",
      insulation: 200,
      sex: "Unisex",
    },
    {
      name: "Long Johns 200",
      slug: "longJohns200",
      image: "longJohns200.jpg",
      id: 7342,
      description: "Dlouhé spodky s kruhovým úpletem bez podélných švů. Klínovitá vsázka zvyšuje komfort nošení. Manžety jsou vpletené do tkaniny.",
      colors: "black, dark navy, grey, pine green",
      insulation: 200,
      sex: "Unisex",
    },
    {
      name: "Long Johns with fly 200",
      slug: "longJohnsFly200",
      image: "longJohnsFly200.jpg",
      id: 6342,
      description: "Dlouhé spodky s kruhovým úpletem bez podélných švů. Klínovitá vsázka zvyšuje komfort nošení. Manžety jsou vpletené do tkaniny. S poklopcem.",
      colors: "black, dark navy, pine green",
      insulation: 200,
      sex: "Pánské",
    },
    {
      name: "Full Zip Jacket 400",
      slug: "fullZipJckt400",
      image: "fullZipJckt400-autumn_red.jpg",
      id: 7234,
      description: "Celorozepínací mikina s vysokým, dvojitě zesíleným límcem a s prodlouženým zadním dílem. Manžety mají dírky na palce. Na límci je vpletené logo Woolpower.",
      colors: "black, dark navy, grey, pine green, autumn red, rust red, forest green",
      insulation: 400,
      sex: "Unisex",
    },
    {
      name: "Zip Turtleneck 400",
      slug: "zipTurtleneck400",
      image: "zipTurtleneck400.jpg",
      id: 7224,
      description: "Rolák s dlouhým rukávem a krátkým zipem, je vyroben z kruhového úpletu a nemá podélné švy. Zadní strana je delší pro zvýšení komfortu nošení. Manžety jsou vpletené do tkaniny.",
      colors: "black, dark navy, pine green",
      insulation: 400,
      sex: "Unisex",
    },
    {
      name: "Vest 400",
      slug: "vest400",
      image: "vest400-navy.jpg",
      id: 7244,
      description: "Celorozepínací vesta s vysokým, dvojitě zesíleným límcem s vpleteným logem Woolpower. Vyrobena z kruhového úpletu s rovným spodním lemem. ",
      colors: "black, dark navy, grey, pine green",
      insulation: 400,
      sex: "Unisex",
    },
    {
      name: "Long Johns 400",
      slug: "longJohns400",
      image: "longJohns400.jpg",
      id: 7344,
      description: "Dlouhé spodky s kruhovým úpletem bez podélných švů. Klínovitá vsázka zvyšuje komfort nošení. Manžety jsou vpletené do tkaniny.",
      colors: "black, dark navy, pine green",
      insulation: 400,
      sex: "Unisex",
    },
    {
      name: "Long Johns with fly 400",
      slug: "longJohnsFly400",
      image: "longJohnsFly400.jpg",
      id: 6344,
      description: "Dlouhé spodky s kruhovým úpletem bez podélných švů. Klínovitá vsázka zvyšuje komfort nošení. Manžety jsou vpletené do tkaniny. S poklopcem.",
      colors: "black, pine green",
      insulation: 400,
      sex: "Pánské",
    },
    {
      name: "Full Zip Jacket 600",
      slug: "fullZipJckt600",
      image: "fullZipJckt600.jpg",
      id: 7236,
      description: "Celorozepínací mikina s vysokým, dvojitě zesíleným límcem a s prodlouženým zadním dílem. Manžety mají dírky na palce. ",
      colors: "black, dark navy, pine green",
      insulation: 600,
      sex: "Unisex",
    }
  ]
}