export default {
  produkty: [
    {
      name: "Zip Turtleneck 200",
      slug: "zipTurtleneck200",
      image: "zipTurtleneck200.jpg",
      id: 1,
      description: "Rolák je vhodný do chladnějšíh počasí. Díky zipu lze regulovat ventilaci. Raglánové rukávy a ploché švy dodají na pohodlnosti při nošení.",
      colors: "black, dark navy, grey, pine green",
      insulation: 200,
    },
    {
      name: "Crewneck 200",
      slug: "crewneck200",
      image: "crewneck200.jpg",
      id: 2,
      description: "Rolák je vhodný do chladnějšíh počasí. Díky zipu lze regulovat ventilaci. Raglánové rukávy a ploché švy dodají na pohodlnosti při nošení.",
      colors: "black, dark navy, grey, pine green",
      insulation: 200,
    },
    {
      name: "Tee 200",
      slug: "tee200",
      image: "tee200.jpg",
      id: 3,
      description: "Rolák je vhodný do chladnějšíh počasí. Díky zipu lze regulovat ventilaci. Raglánové rukávy a ploché švy dodají na pohodlnosti při nošení.",
      colors: "black, dark navy, grey, pine green",
      insulation: 200,
    },
    {
      name: "Long Johns 200",
      slug: "longJohns200",
      image: "longJohns200.jpg",
      id: 4,
      description: "Rolák je vhodný do chladnějšíh počasí. Díky zipu lze regulovat ventilaci. Raglánové rukávy a ploché švy dodají na pohodlnosti při nošení.",
      colors: "black, dark navy, grey, pine green",
      insulation: 200,
    },
    {
      name: "Long Johns with fly 200",
      slug: "longJohnsFly200",
      image: "longJohnsFly200.jpg",
      id: 5,
      description: "Rolák je vhodný do chladnějšíh počasí. Díky zipu lze regulovat ventilaci. Raglánové rukávy a ploché švy dodají na pohodlnosti při nošení.",
      colors: "black, dark navy, pine green",
      insulation: 200,
    },
    {
      name: "Full Zip Jacket 400",
      slug: "fullZipJckt400",
      image: "fullZipJckt400.jpg",
      id: 6,
      description: "Rolák je vhodný do chladnějšíh počasí. Díky zipu lze regulovat ventilaci. Raglánové rukávy a ploché švy dodají na pohodlnosti při nošení.",
      colors: "black, dark navy, grey, pine green",
      insulation: 400,
    },
    {
      name: "Zip Turtleneck 400",
      slug: "zipTurtleneck400",
      image: "zipTurtleneck400.jpg",
      id: 7,
      description: "Rolák je vhodný do chladnějšíh počasí. Díky zipu lze regulovat ventilaci. Raglánové rukávy a ploché švy dodají na pohodlnosti při nošení.",
      colors: "black, dark navy, pine green",
      insulation: 400,
    },
    {
      name: "Vest 400",
      slug: "vest400",
      image: "vest400.jpg",
      id: 8,
      description: "Rolák je vhodný do chladnějšíh počasí. Díky zipu lze regulovat ventilaci. Raglánové rukávy a ploché švy dodají na pohodlnosti při nošení.",
      colors: "black, dark navy, grey, pine green",
      insulation: 400,
    },
    {
      name: "Long Johns 400",
      slug: "longJohns400",
      image: "longJohns400.jpg",
      id: 9,
      description: "Rolák je vhodný do chladnějšíh počasí. Díky zipu lze regulovat ventilaci. Raglánové rukávy a ploché švy dodají na pohodlnosti při nošení.",
      colors: "black, dark navy, pine green",
      insulation: 400,
    },
    {
      name: "Long Johns with fly 400",
      slug: "longJohnsFly400",
      image: "longJohnsFly400.jpg",
      id: 10,
      description: "Rolák je vhodný do chladnějšíh počasí. Díky zipu lze regulovat ventilaci. Raglánové rukávy a ploché švy dodají na pohodlnosti při nošení.",
      colors: "black, pine green",
      insulation: 400,
    },
    {
      name: "Full Zip Jacket 600",
      slug: "fullZipJckt600",
      image: "fullZipJckt600.jpg",
      id: 11,
      description: "Rolák je vhodný do chladnějšíh počasí. Díky zipu lze regulovat ventilaci. Raglánové rukávy a ploché švy dodají na pohodlnosti při nošení.",
      colors: "black, dark navy, pine green",
      insulation: 600,
    }
  ]
}